TrajectoryPlannerROS:
  max_vel_x: 2.2
  min_vel_x: -2.2
  max_vel_theta: 2.2
  min_in_place_vel_theta: -1.8

  acc_lim_theta: 1.0
  acc_lim_x: 1.4
  acc_lim_y: 1.4

  sim_time: 1.0
  sim_granularity: 0.75
  
  meter_scoring: true
  pdist_scale: 0.8
  gdist_scale : 0.8
  occdist_scale : 0.01
  publish_cost_grid_pc: false

  holonomic_robot: false
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.05
  latch_xy_goal_tolerance: false
  controller_frequency: 20.0
  escape_vel: -0.2
  oscillation_reset_dist: 0.1
  heading_scoring_timestep: 1.2