map_type: costmap

obstacle_range: 5.0
raytrace_range: 8.0
footprint: [ [-0.2, -0.4], [0.2, -0.4], [0.2, 0.4], [-0.2, 0.4] ]
transform_tolerance: 1.3

robot_radius: 0.21
inflation_radius: 0.55
cost_scaling_factor : 5.0

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /shreyas_bot/laser/scan, marking: true, clearing: true}
point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}