TrajectoryPlannerROS:
  max_vel_x: 2.0
  min_vel_x: -2.0
  max_vel_theta: 1.5
  min_in_place_vel_theta: -1.5

  acc_lim_theta: 0.8
  acc_lim_x: 1.0
  acc_lim_y: 1.0

  sim_time: 1.0
  sim_granularity: 0.75
  
  meter_scoring: false
  pdist_scale: 0.6
  gdist_scale : 0.6
  occdist_scale : 0.01
  publish_cost_grid_pc: false

  holonomic_robot: false
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.0.05
  latch_xy_goal_tolerance: false
  controller_frequency: 10.0
  escape_vel: -0.1
  oscillation_reset_dist: 0.1
  heading_scoring_timestep: 1.2