map_type: costmap

obstacle_range: 5.0
raytrace_range: 8.0

transform_tolerance: 1.5

robot_radius: 0.1
inflation_radius: 0.5
cost_scaling_factor : 5.0

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}