local_costmap:
  global_frame: odom
  robot_base_frame: robot_footprint
  transform_tolerance: 1.5
  update_frequency: 10.0
  publish_frequency: 10.0
  width: 10.0
  height: 10.0
  resolution: 0.05
  static_map: false
  rolling_window: true